# Generated by Django 3.2.16 on 2024-04-07 20:01

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20240407_2300'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='user_following_unique',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('user', django.db.models.expressions.F('following'))), name='user_cannot_follow_self'),
        ),
    ]
